# spring.datasource.url=jdbc:mysql://localhost:3306/javabatch
# spring.datasource.username=root
# spring.datasource.password=Zensar@123
# spring.jpa.hibernate.ddl-auto=create


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
    password: Zensar@123
  jpa: 
   hibernate:
     ddl-auto: create
   show-sql: true
   properties:
    hibernate:
     format_sql: true
     #dialect: org.hibernate.dialect.MySQLDialect
     


management:
  endpoints:
   web:
     exposure:
       include:
       - "*"
       exclude:
       - beans
     base-path: /myactuator
       
  endpoint:
    shutdown:
      enabled: true   
      
      
  info:
    build:
      enabled: true
      
    git:
      enabled: true
      
    env:
      enabled: true
      
info:
  createdBy: vinod kumar
  modified: 22jun2022
  
  
logging:
  level:
    com:
     zensar: debug  
 
     